import { describe, expect, it } from 'vitest'
import { command } from '../lib/demo-store'

describe('golden mocked workflow', () => {
  it('moves from lead search to proposal delivery without external providers', async () => {
    const leads = await command({ command: 'latest leads' })
    expect(leads.leads).toHaveLength(4)
    await command({ command: 'qualify demo-1048', leadId: 'demo-1048' })
    const preview = await command({ command: 'send outreach', scenario: 'interested' })
    expect(preview.message).toContain('To: demo@example.test')
    expect(preview.job?.emailStatus).toBe('pending_confirmation')
    const outreach = await command({ command: '', actionId: preview.actions?.[0].id, scenario: 'interested' })
    expect(outreach.job?.emailStatus).toBe('replied')
    await command({ command: 'green light' })
    const waiting = await command({ command: 'upload report' })
    expect(waiting.job?.measurements).toBeUndefined()
    await command({ command: 'use demo report' })
    const measurements = await command({ command: 'approve measurements' })
    expect(measurements.job?.measurements?.confidence).toBeGreaterThan(0.9)
    expect(measurements.job?.measurements?.totalAreaSqFt).toBe(9572)
    expect(measurements.job?.measurements?.dominantPitch).toBe('12/12')
    const pricing = await command({ command: 'calculate takeoff' })
    expect(pricing.actions?.map((item) => item.title)).toEqual(['Saved pricing', 'Demo pricing', 'Ask distributor'])
    const takeoff = await command({ command: '', actionId: pricing.actions?.[1].id })
    expect(takeoff.job?.takeoff?.totalCents).toBeGreaterThan(0)
    expect(takeoff.message).toContain('/api/takeoffs/')
    const proposalPreview = await command({ command: 'generate proposal' })
    expect(proposalPreview.message).toContain('To: demo@example.test')
    expect(proposalPreview.job?.stage).toBe('proposal')
    const proposal = await command({ command: '', actionId: proposalPreview.actions?.[0].id })
    expect(proposal.job?.stage).toBe('sent')
    expect(proposal.job?.emailStatus).toBe('delivered')
    expect(proposal.job?.pendingEmail).toBeUndefined()
  })

  it('previews a distributor request before applying the simulated quote', async () => {
    const from = '+15550009999'
    await command({ command: 'latest leads', from })
    let result = await command({ command: 'qualify demo-1048', leadId: 'demo-1048', from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    const distributorMenu = await command({ command: '', actionId: result.actions?.[2].id, from })
    expect(distributorMenu.message).toContain('ABC Supply')
    expect(distributorMenu.message).toContain('SRS Distribution')
    expect(distributorMenu.message).toContain('Beacon Building Products')
    expect(distributorMenu.actions).toHaveLength(3)
    const emailPreview = await command({ command: '', actionId: distributorMenu.actions?.[0].id, from })
    expect(emailPreview.message).toContain('To: pricing.iowacity@abcsupply.example')
    expect(emailPreview.job?.takeoff).toBeUndefined()
    const priced = await command({ command: '', actionId: emailPreview.actions?.[0].id, from })
    expect(priced.job?.takeoff?.priceBookVersion).toBeTruthy()
    expect(priced.message).toContain('/api/takeoffs/')
  })

  it('keeps outreach unsent after cancellation and allows a fresh preview', async () => {
    const from = '+15550008888'
    await command({ command: 'latest leads', from })
    let result = await command({ command: 'qualify demo-1048', leadId: 'demo-1048', from })
    result = await command({ command: '', actionId: result.actions?.[0].id, from })
    const canceled = await command({ command: '', actionId: result.actions?.[1].id, from })
    expect(canceled.job?.emailStatus).toBe('draft')
    expect(canceled.job?.pendingEmail).toBeUndefined()
    expect(canceled.actions?.[0].id).toContain('preview-outreach')
    const freshPreview = await command({ command: '', actionId: canceled.actions?.[0].id, from })
    expect(freshPreview.message).toContain('To: demo@example.test')
  })
})
